[package]
name = "whatsapp-business-rs"
version = "0.1.1"
edition = "2021"
authors = ["Victor <victorayo206@example.com>"]
description = "A modern Rust SDK for the WhatsApp Business Platform — send messages, manage catalogs, integrate webhooks, and build automated business flows with type safety and async elegance."
license = "MIT OR Apache-2.0"
repository = "https://github.com/veecore/whatsapp-business-rs"
documentation = "https://docs.rs/whatsapp-business-rs"
readme = "README.md"
keywords = ["whatsapp", "rust", "sdk", "messaging", "async"]
categories = ["api-bindings", "web-programming::http-client", "network-programming", "asynchronous"]
homepage = "https://github.com/veecore/whatsapp-business-rs"
build = "build.rs"
exclude = [".github", "assets"]

[dependencies]
reqwest = { version = "0.11", features = ["json", "multipart"] }
tokio = { version = "1.0", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
thiserror = "2.0.12"
async-stream = "0.3.6"
axum = "0.8.4"
hmac = "0.12.1"
sha2 = "0.10.9"
hex = "0.4.3"
futures = "0.3.31"
subtle = "2.6.1"
paste = "1.0.15"
infer = {version = "0.19.0", default-features = false}
base64 = "0.22.1"

[features]
incoming_message_ext = []