[package]
name = "whatsapp-business-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = { version = "0.11", features = ["json", "multipart"] }
tokio = { version = "1.0", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
thiserror = "2.0.12"
async-stream = "0.3.6"
axum = "0.8.4"
hmac = "0.12.1"
sha2 = "0.10.9"
hex = "0.4.3"
futures = "0.3.31"
subtle = "2.6.1"
paste = "1.0.15"
infer = {version = "0.19.0", default-features = false}
base64 = "0.22.1"

[features]
incoming_message_ext = []
nightly = []