name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          profile: minimal

      - name: Run tests
        run: cargo test --all --all-features

      - name: Format check
        run: cargo fmt --all -- --check

      - name: Lint
        run: cargo clippy --all --all-targets -- -D warnings

      - name: Build
        run: cargo build --release
